version: '3.8'

services:
  # ===========================================
  # MONGODB - Comment/Uncomment based on setup
  # ===========================================
  
  # Option 1: Use Docker MongoDB (for AWS/Production)
  # Uncomment this section when deploying to AWS
  # mongodb:
  #   image: mongo:7.0
  #   restart: unless-stopped
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: bonkcapital2024
  #     MONGO_INITDB_DATABASE: lending_platform
  #   volumes:
  #     - mongodb_data:/data/db
  #     - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  #   networks:
  #     - bonkcapital-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # ===========================================
      # DATABASE CONNECTION - Choose one:
      # ===========================================
      
      # Option 1: Connect to your existing local MongoDB (CURRENT - for development with existing data)
      MONGO_URI: mongodb://host.docker.internal:27017/lending_platform
      
      # Option 2: Connect to Docker MongoDB (for AWS/Production)
      # MONGO_URI: mongodb://admin:bonkcapital2024@mongodb:27017/lending_platform?authSource=admin
      
      PORT: 8080
    # depends_on:
    #   - mongodb  # Uncomment when using Docker MongoDB
    networks:
      - bonkcapital-network
    # For connecting to host machine's MongoDB from Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"

# Uncomment when using Docker MongoDB
# volumes:
#   mongodb_data:

networks:
  bonkcapital-network:
    driver: bridge